version: 0.0.{build}
image: Ubuntu1804
configuration: Release
platform:
- x64
cache: src/packages
before_build:
- sh: cd src
- sh: nuget restore
build_script:
  sh: 
    gcc -m64 -c -O2 -Wall -fPIC -DLINUX plugin.cpp
    gcc -m64 -o ChannelWatcher_amd64.so -shared plugin.o
deploy: off