version: 0.0.{build}
image: Ubuntu1804
configuration: Release
platform:
- x64
cache: src/packages
before_build:
- cmd: cd src
- cmd: nuget restore
build_script:
  sh: 
    gcc -m64 -c -O2 -Wall -fPIC -DLINUX plugin.c
    gcc -m64 -o xyz_plugin_linux_amd64.so -shared plugin.o
build:
  project: src/ts3_channel_watcher.sln
  verbosity: minimal
deploy: off