version: 0.0.{build}
max_jobs: 4
image:
  - Ubuntu1804
  - Visual Studio 2019
configuration: 
  - Release
platform:
  - x64
  - x86
cache: src/packages
install:
  - cd src
  - nuget restore
build:
  project: src/ts3_channel_watcher.sln
  verbosity: minimal
for:
  - matrix:
      only:
        - image: Ubuntu1804
        - platform: x64
    build_script:
      - sh: gcc -m64 -I../include -c -O2 -Wall -fPIC -DLINUX plugin.cpp
      - sh: gcc -m64 -o ChannelWatcher_x64.so -shared plugin.o
  - matrix:
      only:
        - image: Ubuntu1804
        - platform: x86
    build_script:
      - sh: gcc -m32 -I../include -c -O2 -Wall -fPIC -DLINUX plugin.cpp
      - sh: gcc -m32 -o ChannelWatcher_x86.so -shared plugin.o
deploy: off